# Generated by Django 5.2.1 on 2025-05-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_summary', models.CharField(max_length=300)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('education', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('linkedin', models.URLField()),
                ('preferred_location', models.ManyToManyField(to='accounts.location')),
                ('preferred_roles', models.ManyToManyField(to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
