# Generated by Django 5.2.1 on 2025-05-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_location',
            field=models.ManyToManyField(blank=True, to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_roles',
            field=models.ManyToManyField(blank=True, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prof_summary',
            field=models.CharField(default='A passionate professional.', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(default='Not specified', max_length=300),
        ),
    ]
